import adafruit_blinka.microcontroller.generic_linux.libgpiod_pin

SCL: adafruit_blinka.microcontroller.generic_linux.libgpiod_pin.Pin
SDA: adafruit_blinka.microcontroller.generic_linux.libgpiod_pin.Pin
